//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel_Demo.RocketService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RocketService.IRocketService")]
    public interface IRocketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRocketService/increaseAltitude", ReplyAction="http://tempuri.org/IRocketService/increaseAltitudeResponse")]
        double[] increaseAltitude(double time, double altitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRocketService/increaseAltitude", ReplyAction="http://tempuri.org/IRocketService/increaseAltitudeResponse")]
        System.Threading.Tasks.Task<double[]> increaseAltitudeAsync(double time, double altitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRocketService/GetTelemetryData", ReplyAction="http://tempuri.org/IRocketService/GetTelemetryDataResponse")]
        double[] GetTelemetryData(double timeToOrbit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRocketService/GetTelemetryData", ReplyAction="http://tempuri.org/IRocketService/GetTelemetryDataResponse")]
        System.Threading.Tasks.Task<double[]> GetTelemetryDataAsync(double timeToOrbit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRocketServiceChannel : Intel_Demo.RocketService.IRocketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RocketServiceClient : System.ServiceModel.ClientBase<Intel_Demo.RocketService.IRocketService>, Intel_Demo.RocketService.IRocketService {
        
        public RocketServiceClient() {
        }
        
        public RocketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RocketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RocketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RocketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double[] increaseAltitude(double time, double altitude) {
            return base.Channel.increaseAltitude(time, altitude);
        }
        
        public System.Threading.Tasks.Task<double[]> increaseAltitudeAsync(double time, double altitude) {
            return base.Channel.increaseAltitudeAsync(time, altitude);
        }
        
        public double[] GetTelemetryData(double timeToOrbit) {
            return base.Channel.GetTelemetryData(timeToOrbit);
        }
        
        public System.Threading.Tasks.Task<double[]> GetTelemetryDataAsync(double timeToOrbit) {
            return base.Channel.GetTelemetryDataAsync(timeToOrbit);
        }
    }
}
