//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel_Demo.PayloadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PayloadService.IPayloadService")]
    public interface IPayloadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayloadService/GetPayloadData", ReplyAction="http://tempuri.org/IPayloadService/GetPayloadDataResponse")]
        double[] GetPayloadData(string type, int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayloadService/GetPayloadData", ReplyAction="http://tempuri.org/IPayloadService/GetPayloadDataResponse")]
        System.Threading.Tasks.Task<double[]> GetPayloadDataAsync(string type, int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayloadService/GetPayloadTelemetryData", ReplyAction="http://tempuri.org/IPayloadService/GetPayloadTelemetryDataResponse")]
        double[] GetPayloadTelemetryData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayloadService/GetPayloadTelemetryData", ReplyAction="http://tempuri.org/IPayloadService/GetPayloadTelemetryDataResponse")]
        System.Threading.Tasks.Task<double[]> GetPayloadTelemetryDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPayloadServiceChannel : Intel_Demo.PayloadService.IPayloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayloadServiceClient : System.ServiceModel.ClientBase<Intel_Demo.PayloadService.IPayloadService>, Intel_Demo.PayloadService.IPayloadService {
        
        public PayloadServiceClient() {
        }
        
        public PayloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double[] GetPayloadData(string type, int index) {
            return base.Channel.GetPayloadData(type, index);
        }
        
        public System.Threading.Tasks.Task<double[]> GetPayloadDataAsync(string type, int index) {
            return base.Channel.GetPayloadDataAsync(type, index);
        }
        
        public double[] GetPayloadTelemetryData() {
            return base.Channel.GetPayloadTelemetryData();
        }
        
        public System.Threading.Tasks.Task<double[]> GetPayloadTelemetryDataAsync() {
            return base.Channel.GetPayloadTelemetryDataAsync();
        }
    }
}
